sonar.projectName=WOMS
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

sonar.sources=cmd,internal,web,scripts,deploy/helm/woms
sonar.tests=cmd,internal,web,deploy/helm/woms
sonar.test.inclusions=**/*_test.go,**/*.test.mjs

sonar.exclusions=**/node_modules/**,**/coverage/**,**/charts/**,deploy/helm/woms/Chart.lock
sonar.coverage.exclusions=cmd/**,**/*_test.go,**/*.test.mjs,deploy/**,scripts/**

sonar.go.coverage.reportPaths=coverage.out
sonar.javascript.lcov.reportPaths=coverage/lcov.info
