{{- if and .Values.keda.enabled .Values.web.metrics.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "woms.fullname" . }}-web
  labels:
    {{- include "woms.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "woms.fullname" . }}-web
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  advanced:
    horizontalPodAutoscalerConfig:
      name: {{ include "woms.fullname" . }}-web-hpa
      behavior:
        scaleUp:
          stabilizationWindowSeconds: {{ .Values.keda.hpa.scaleUp.stabilizationWindowSeconds }}
          policies:
            - type: Percent
              value: {{ .Values.keda.hpa.scaleUp.percent }}
              periodSeconds: {{ .Values.keda.hpa.scaleUp.periodSeconds }}
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.keda.hpa.scaleDown.stabilizationWindowSeconds }}
          policies:
            - type: Percent
              value: {{ .Values.keda.hpa.scaleDown.percent }}
              periodSeconds: {{ .Values.keda.hpa.scaleDown.periodSeconds }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: {{ tpl .Values.keda.prometheus.serverAddress . | quote }}
        metricName: {{ .Values.keda.prometheus.metricName | quote }}
        query: {{ tpl .Values.keda.prometheus.query . | quote }}
        threshold: {{ .Values.keda.prometheus.threshold | quote }}
{{- end }}
