apiVersion: v1
kind: Service
metadata:
  name: {{ include "woms.fullname" . }}-api
  labels:
    {{- include "woms.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "woms.fullname" . }}-web
  labels:
    {{- include "woms.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 8080
      targetPort: http
    {{- if .Values.web.metrics.enabled }}
    - name: metrics
      port: {{ .Values.web.metrics.port }}
      targetPort: metrics
    {{- end }}
